/// Flutter icons PertaniIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PertaniIcon
///      fonts:
///       - asset: fonts/PertaniIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PertaniIcon {
  PertaniIcon._();

  static const _kFontFam = 'PertaniIcon';

  static const IconData icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData flour = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData transaction = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData google_plus = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData filter_filled_tool_symbol = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData delivery_truck = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData business = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData completed = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData confirmation = const IconData(0xe80e, fontFamily: _kFontFam);
}
